# Generated by Django 5.0.3 on 2024-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produtos_registrado_por_produtos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='produtos',
            name='vendedor_responsavel',
            field=models.CharField(blank=True, max_length=194, null=True, verbose_name='Vendedor Responsável'),
        ),
    ]
