# Generated by Django 5.0.3 on 2024-03-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('valor_produto', models.CharField(max_length=200, verbose_name='Valor')),
                ('data_venda', models.DateField(verbose_name='Data da venda')),
                ('quantidade_venda', models.PositiveSmallIntegerField(verbose_name='Quantidade de produtos')),
                ('vendedor', models.CharField(blank=True, max_length=194, null=True, verbose_name='Vendedor')),
                ('horario_venda', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Horário da venda')),
                ('supervisor', models.CharField(blank=True, max_length=194, verbose_name='Supervisor')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produtos', verbose_name='Responsável pelo registro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
            },
        ),
    ]
