# Generated by Django 5.0.3 on 2024-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_registrado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='registrado_por',
        ),
        migrations.AddField(
            model_name='produtos',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando a venda'), ('NO_ESTOQUE', 'No estoque'), ('FINALIZADA', 'Venda finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
